- lib/cli-context.js
- lib/create-app.js
- lib/stripes-cli.js
- lib/yarn.js
- package.json
Adds support to check for own updates and yarn install dependencies after creating a new app
> Update and install

- README.md
- lib/cli-context.js
- lib/cli-test-module.js
- lib/commands/alias.js
- lib/commands/build.js
- lib/commands/common-options.js
- lib/commands/new.js
- lib/commands/serve.js
- lib/commands/status.js
- lib/commands/test.js
- lib/generate-platform.js
- lib/integration-tests.js
- lib/stripes-cli.js
- lib/stripes-platform.js
- lib/webpack-common.js
- package.json
- resources/ui-app/test/ui-testing/demo.js
Organize, document, and expand commands for CLI prototype, STRIPES-484
> Command organization

- lib/commands/build.js
- lib/commands/serve.js
- lib/commands/test.js
Defaults can be overridden by defining NODE_ENV
> Assign defaults when NODE_ENV is not set

- lib/webpack-common.js
- test/webpack-common.spec.js
Add missing resolve paths for when stripes-core is aliased, follow-up to STCLI-13
> Add missing resolve paths for when stripes-core is aliased

- lib/test/webpack-config.js
> Add missing stripes-translations-plugin to test config

- lib/commands/test/karma.js
- lib/commands/test/nightmare.js
- lib/test/run-karma.js
- lib/test/run-nightmare.js
> File rename to match previous work

- lib/commands/app/create.js
- resources/ui-app/README.md
- resources/ui-app/package.json
- resources/ui-app/src/components/new-app-greeting/new-app-greeting.js
- resources/ui-app/src/settings/general-settings.js
- resources/ui-app/src/settings/index.js
- resources/ui-app/src/settings/some-feature-settings.js
- resources/ui-app/translations/en.json
Miscellaneous cleanup of new ui-app templates prior to releasing v1
> STCLI-25 react and cleanup

- CHANGELOG.md
- doc/commands.md
- lib/stripes-cli.js
Report unrecognized commands and offer suggestions.
Enable option to generate Yargs bash completion script.
> STCLI-36 uknown commands

- doc/commands.md
- lib/stripes-cli.js
Disable yargs completion due to conflict with recommendCommands output
> STCLI-36 disable completion

- .vscode/launch.json
- CHANGELOG.md
- doc/dev-guide.md
- doc/user-guide.md
- lib/cli/config.js
- lib/cli/context.js
- lib/cli/logger.js
- lib/cli/main-handler.js
- lib/cli/questions.js
- lib/cli/stripes-core.js
- lib/environment/development.js
- lib/okapi/okapi-client.js
- lib/platform/alias-service.js
- lib/platform/stripes-platform.js
- lib/stripes-cli.js
- lib/webpack-common.js
- package.json
- test/webpack-common.spec.js
Include documentation for viewing debug output and debugging stripes CLI commands and builds.
Wrap existing usage of debug and further instrument the CLI for logging.
> STCLI-47 debug

- CHANGELOG.md
- lib/commands/test/nightmare.js
- lib/test/run-nightmare.js
Also move exit on failure up to the command
> STCLI-49 Exit process when Nightmare tests pass

- CHANGELOG.md
- doc/user-guide.md
Fixes [STCLI-50](https://issues.folio.org/browse/STCLI-50)
> Correctly quote install options

- lib/environment/inventory.js
https://issues.folio.org/browse/STRIPES-541
> Add My Profile. Part of STRIPES-541

- CHANGELOG.md
- lib/commands/test/nightmare.js
replaced iteration over array with iteration over object.  Also added more specific text output to signal failure or success.
> fixed issue with iterating over array that was causing logic to fail for detecting error case

- lib/cli/context.js
- lib/commands/serve.js
Bug fix from https://github.com/folio-org/stripes-cli/pull/112
> Allow platforms to serve

- lib/environment/inventory.js
ERM work is kicking off so adding its modules to be available for pull.
_I think this is all I need to do for that??_
> Added ERM UI modules

- lib/cli/context.js
- lib/okapi/module-service.js
- lib/okapi/okapi-client.js
- lib/stripes-cli.js
- lib/test/nightmare-service.js
- lib/webpack-common.js
- package.json
- test/cli/context.spec.js
`import/order` and `lines-between-class-members` were the only rules prompting changes.
> Lint lib with eslint-config-stripes-3.2.1

- resources/platform/package.json
- resources/ui-app/package.json
- resources/ui-app/src/components/greeting-modal/greeting-modal.js
- resources/ui-app/src/components/new-app-greeting/new-app-greeting.js
- resources/ui-app/src/routes/application.js
- resources/ui-app/src/routes/example-page.js
- resources/ui-app/src/settings/general-settings.js
- resources/ui-app/src/settings/index.js
- resources/ui-app/src/settings/some-feature-settings.js
- resources/ui-app/test/ui-testing/demo.js
Primary motivation: https://issues.folio.org/browse/STCOM-330
While I was in there, updated `package.json` versions and addressed some linting issues I'd seen in other repos.
> STCOM-330 Update blueprint

- CHANGELOG.md
- doc/commands.md
- lib/commands/mod/install.js
- lib/commands/mod/list.js
- lib/commands/mod/view.js
- lib/okapi/module-service.js
- lib/okapi/okapi-repository.js
> STCLI-79 mod updates

- doc/commands.md
- doc/dev-guide.md
- doc/user-guide.md
The only typo that i could find.
> FOLIO-398 tidy 5

- lib/environment/inventory.js
Added/tweaked the repos available:
```
- M ui-erm -> ui-agreements
- A ui-erm-usage
- A platform-erm
```
> Handled rename of ui-erm to ui-agreements

- lib/create-app.js
- lib/environment/development.js
- package.json
- resources/ui-app/package.json
- resources/workspace/package.json
According to [STCLI-109](https://issues.folio.org/browse/STCLI-109), CLI should be included as a devDependency of the app and workspace's package.json
> STCLI-109: Dynamically include CLI as devDependency of app and workspace

- lib/okapi/module-service.js
Correct mix-up in which the front and back end filter calls were swapped
> STCLI-116 filter fix

- CHANGELOG.md
- doc/backend-guide.md
- doc/commands.md
- doc/troubleshooting.md
- doc/user-guide.md
- lib/commands/mod/perms.js
- lib/commands/perm/assign.js
- lib/commands/perm/list.js
- lib/commands/perm/view.js
- lib/commands/platform/backend.js
- lib/okapi/module-service.js
- lib/okapi/permission-service.js
- test/okapi/module-service.spec.js
- test/okapi/permission-service.spec.js
- test/platform/stripes-platform.spec.js
This adds new command to list permissions for modules, allowing them to be piped to commands for assignment.  Logic is shared with platform backend command to facilitate provisioning a back-end for a platform.  Test coverage has been increased for module and permission services.
> STCLI-115 permissions

- CHANGELOG.md
- doc/commands.md
- lib/commands/mod/add.js
- lib/okapi/module-service.js
- test/okapi/module-service.spec.js
This enables `mod add` to accept an array existing module descriptor JSON via stdin.
> STCLI-127 mod add

- lib/environment/inventory.js
- Added `stripes-erm-components`, `ui-plugin-find-agreement`, and `ui-plugin-find-license`.
- Alpha-sorted the lists
> Updated inventory.js

- resources/ui-app/CHANGELOG.md
- resources/ui-app/package.json
- resources/ui-app/src/routes/application.js
- resources/ui-app/src/routes/example-page.js
Minor updates to the ui-module blueprint to resolve lint errors and versions referenced in the generated ui-module
> Blueprint updates

- CHANGELOG.md
- lib/environment/inventory.js
Provide support for additional apps and libraries.
Refs [STCLI-142](https://issues.folio.org/browse/STCLI-142)
> STCLI-142 support additional apps/libraries

- .eslintrc
- lib/stripes-cli.js
- package.json
Also ignored new rules that conflict with existing stripes-cli implementation
> Upgraded eslint to 6.2.1 and eslint-config-stripes to 5

- CHANGELOG.md
- lib/cli/generate-module-descriptor.js
- test/okapi/descriptor-service.spec.js
> Correct Okapi syntax for optional dependencies

- lib/cli/stripes-core.js
- package.json
This reverts commit f58dab7e143bf301cc8ba12242de9fffb9e38a19.
> Revert "STRIPES-730: Breakup stripes-cli and stripes-core"

- CHANGELOG.md
- package.json
Refs [STCLI-185](https://issues.folio.org/browse/STCLI-185)
> STCLI-185 stripes-webpack v2 (react 17)

- package.json
This PR will go together with changes in stripes-core and stripes-connect:
folio-org/stripes-core#986
folio-org/stripes-connect#164
> Remove rxjs dependencies

- CHANGELOG.md
- lib/test/karma-service.js
- package.json
- test/test/karma-service.spec.js
This reverts commit 1eebaf05c8e9dccc2460a82d35a8ed03b9df6739.
> Revert "STCLI-187: Update webpack to v5 (#270)"

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
Correctly locate test output so SonarCloud can find it.
> correct test output locations in CI reports

- CHANGELOG.md
- package.json
Refs [STCLI-260](https://folio-org.atlassian.net/browse/STCLI-260)
> STCLI-260 bump NodeJS to v20
