folio-org/stripes-cli

- lib/cli-config.js
- lib/commands/status.js
- lib/platform/platform-config.js
- lib/platform/stripes-platform.js
Consolidate alias configuration into new CLI config file.  This keeps CLI concerns separate from tenant-specific stripes configuration.
> Cli config aliases

- package.json
Fixes 404's running Karma unit tests discussed in STRIPES-494.
The cause appears to a defect found in versions of `karma-webpack` greater than 2.0.6.
https://github.com/webpack-contrib/karma-webpack/issues/289
The 404's may be related to `/_karma_webpack_/`paths used for the in-memory file system. Comparing the verbose webpack output of my NPM-installed CLI with that of my Yarn-installed CLI, I came across a discrepancy in `PublicPath` with the Yarn version was pointing to a nonexistent directory in the temporary `/var/folders/...` path on disk.
As a global NPM install, the existing package-lock.json is respected which happens to have karma-webpack already set at 2.0.6.  Once we started using Stripes CLI with ui-eholdings via Yarn, the latest version of karma-webpack was pulled in …
> Lock karma-webpack to 2.0.6 to resolve 404's running unit tests

- lib/commands/test.js
- lib/test/unit.js
- package-lock.json
- package.json
New CLI `--karma` option enables karma-specific options to be passed on the command line using dot notation.  For example, `--karma.singleRun` and `--karma.browsers=Chrome`.
The CLI's plugin pattern has been extended to the `test` command providing the same beforeBuild webpack hook available to `serve` and `build`.  This allows for manipulation of the webpack config as necessary during tests.
Finally a correction to the karma config order has been made preventing the base karma configuration from inadvertently overriding values supplied by the app's karma config.
> STCLI-16 karma options

- lib/test/integration.js
- lib/test/unit.js
Probably should consolidate process.exits when introducing more robust error handling
> Apply proper exit code upon unit and e2e test failure

- README.md
- lib/cli/config.js
- lib/commands/alias.js
- lib/commands/serve.js
- lib/commands/test.js
- lib/commands/test/karma.js
- lib/commands/test/nightmare.js
- lib/platform/alias-service.js
- package.json
- test/platform/alias-service.spec.js
This breaks out separate testing workflows into their own commands, rather than switching on the  `--type` option.  Doing so will allow for more tailored CLI options and corresponding help for each.  It also aims to set a better pattern for adding other testing cases like the testing of `stripes-components`, etc. to be addressed in STCLI-19. 
Backwards compatibility remains for the time being with the former `--type` option still honored, but no longer present in readme or help.
> STCLI-19 prep

- CHANGELOG.md
- lib/commands/alias.js
- lib/commands/common-options.js
- lib/commands/serve.js
- lib/commands/test/nightmare.js
- lib/okapi/permission-service.js
- lib/server.js
- lib/stripes-cli.js
- lib/test/cli-test-module.js
- package.json
Implements a simple http-server to serve up a previously created build
Given `stripes build stripes.config.js ouput` created a build.
Then `stripes serve --existing-build output` will serve it up.
> STCLI-26 serve previous builds

- CHANGELOG.md
- README.md
- lib/platform/stripes-platform.js
- test/platform/stripes-platform.spec.js
This change respects the `stripes.config.js` tenant module definition.  If the module configuration is omitted, or no `stripes.config.js` file is provided, then the CLI will revert to automatically adding previously defined aliases as modules.  
This allows for more explicit module definitions without having to alter aliases to add/remove modules for a tenant.  STCLI-18
> STCLI-18 apply alias

- CHANGELOG.md
- README.md
- lib/platform/alias-service.js
- test/platform/alias-service.spec.js
This will ensure alias definitions remain valid for all working directories.
Fixes STCLI-35
> Process aliases relative to .stripesclirc location

- lib/platform/platform-config.js
- lib/platform/stripes-platform.js
- package.json
- test/platform/stripes-platform.spec.js
This will prevent a user-supplied module config from getting overriden by the CLI's generated module config in the CLI's single app context.  Fixes STCLI-44
> Check for an existing module config before assigning one

- CHANGELOG.md
- README.md
- lib/stripes-cli.js
Define a static upgrade message pointing user to the README to avoid misleading upgrade instructions when using Yarn.
> STCLI-34 update instructions

- CHANGELOG.md
- doc/commands.md
- doc/dev-guide.md
- doc/user-guide.md
- lib/cli/context.js
- lib/cli/stdin-handler.js
- lib/commands/app/perms.js
- lib/commands/mod/add.js
- lib/commands/mod/descriptor.js
- lib/commands/mod/disable.js
- lib/commands/mod/enable.js
- lib/commands/mod/install.js
- lib/commands/mod/remove.js
- lib/commands/mod/update.js
- lib/commands/mod/view.js
- lib/commands/perm/assign.js
- lib/commands/workspace.js
- lib/okapi/module-service.js
- lib/okapi/okapi-repository.js
- lib/okapi/permission-service.js
This branch started as a prototype to explore working with multiple modules and Okapi in prep for eventual dynamic module/bundle management.  This yielded a few new commands as well as support for standard input.
* New mod commands to generate descriptors and view tenant modules, STCLI-52
* New app perms command to view permissions for an app, STCLI-54
* Support for stdin, added initially to mod enable/disable and perm assign, STCLI-55
> STCLI-52, STCLI-54, STCLI-55 Okapi experiments

- CHANGELOG.md
- lib/cli/context.js
- lib/cli/global-dirs.js
- package.json
This fix attempts to correct outdated Yarn paths reported by global-dirs on Windows.  If this proves successful for Windows users of stripes-cli, this logic could be contributed back to resolving the original issue within global-dirs itself.
> STCLI-39 Patch global-dirs on Windows with Yarn >=1.5.1

- CHANGELOG.md
- doc/commands.md
- lib/commands/mod/add.js
- lib/commands/mod/descriptor.js
- lib/okapi/module-service.js
This adds the strict option to `mod add` and `mod descriptor` commands.  The value is then passed through module-service and to generateModuleDescriptor() where strict was already taken into account, but not exercised.
> STCLI-59 strict option

- CHANGELOG.md
- package.json
The dependency `get-stdin` was incorrectly identified as a dev-dependency excluding it from a non-dev install of the CLI.
> STCLI-60 stdin fix

- doc/commands.md
- lib/commands/serve.js
- lib/platform/stripes-platform.js
- package.json
- test/platform/stripes-platform.spec.js
https://issues.folio.org/browse/STCLI-62
- Remove `@folio/developer` from dependencies.
- Remove `--uiDev` option.
- Should we cut a major release for this?
> STCLI-62 Remove uiDev option

- CHANGELOG.md
- lib/commands/platform/pull.js
Add some syntax highlighting to make it more obvious when 'git pull' commands fail, but be careful not to anger those folks who might run this in an emacs terminal emulator. You wouldn't like them when they're angry.
> highlight failed 'git pull' commands

- CHANGELOG.md
- lib/test/karma-service.js
Istanbul can also generate an easy-to-read HTML coverage report that's way nicer to work with than the raw `lcov` data.
With `stripes-components`:
Switch to the `lcov` reporter instead of `lcovonly` reporter.
I didn't know of any particular reason to hardcode the filename to `lcov.txt`, so it'll now be the default, `lcov.info`.
> Generate HTML coverage report

- CHANGELOG.md
- Jenkinsfile
- doc/commands.md
- lib/commands/perm/unassign.js
- lib/okapi/okapi-repository.js
- lib/okapi/permission-service.js
This command will unassign permissions from a user.  It supports stdin for working with multiple permissions.  This was to be included in previous work for perm assign, but had been left out.
> STCLI-64 perm unassign

- lib/test/karma-service.js
- Rename existing 'ChromeDocker' custom karma browser launcher to 'ChromeHeadlessDocker'.  
- Add new, non-headless 'ChromeDocker' custom launcher with support to run in Docker.
> STCLI-70: Add new Chrome for Docker custom launcher for Karma

- CHANGELOG.md
- lib/environment/inventory.js
- lib/okapi/module-service.js
stripes-core and stripes-smart-components are now considered when generating module descriptors for a platform
> STCLI-65 extra descriptors

- CHANGELOG.md
- lib/test/webpack-config.js
- package.json
This primarily updates `test/webpack-config.js`, used by Karma tests, to use the new wrapping `StripesWebpackPlugin` rather than adding each Stripes plugin individually.
This config still needs to be moved to stripes-core to avoid going out of sync (STCLI-22).
> STCLI-61 webpack 4

- CHANGELOG.md
- lib/environment/inventory.js
- resources/workspace/package.json
Add `ui-tags` and `platform-core` to the CLI inventory to include them commands like `workspace`, `pull`, and `clean`.
The workspace template has also been updated to consider all directories within, since not all FOLIO projects begin with "ui-" or "stripes-".
> Update CLI inventory

- CHANGELOG.md
- doc/commands.md
- doc/user-guide.md
- lib/commands/common-options.js
- lib/commands/status.js
- lib/platform/platform-config.js
- lib/platform/stripes-platform.js
The number of available translation strings has grown.  This has contributed to increased build times.  One quick way to reduce build times is to build with only one language by specifying a language in `stripes.config.js`.  As reported in STCOR-232,  build times for folio-testing-platform can be reduced by 28% with this technique.
This change to the CLI defines a single language default, `en`, whenever the CLI generates a tenant config.  This applies to apps built in isolation.  When building a platform, the languages array (or absence of it) in a`stripes.config.js` is still respected.
Also included is a command line `--languages` option to override the `en` default or value specified in `stripes.config.js`.  Like any other CLI option, this can be persisted in a `.stripesclirc` config …
> STCOR-232 language option

- CHANGELOG.md
- doc/commands.md
- lib/commands/test/nightmare.js
- lib/test/nightmare-service.js
- test/test/nightmare-service.spec.js
Improve support for invoking platform tests via the CLI by conditionally applying workingDirectory token to each --run segment.  This allows for a platform to invoke regression tests for its apps within.
> STCLI-76 platform tests

- CHANGELOG.md
- lib/okapi/module-service.js
This fix allows non-app stripes.types like settings or plugin to generate module descriptors in isolation via the CLI.
> STCLI-77 Check for platform first

- CHANGELOG.md
- doc/user-guide.md
- lib/commands/app/create.js
- lib/create-app.js
- test/commands/app/create.spec.js
This change updates "app create" command to support use from within a workspace.  The primary difference is in where the subsequent "yarn install" is invoked from.  Tests have been added to cover this command.  STCLI-82
Updates to the user guide are also included to more clearly identify app/platform development prerequisites, STCLI-81
> STCLI-82 app create in workspace

- CHANGELOG.md
- lib/test/karma-service.js
- package.json
- test/test/karma-service.spec.js
- test/test/karma.conf.js
`karma-coverage` still depends on the deprecated [`istanbul`](https://github.com/gotwarlost/istanbul), which hasn't been worked on in two years.
`karma-coverage-istanbul-reporter` switches to using the actively maintained [`istanbul-api`](https://github.com/istanbuljs/istanbuljs) package (used by `nyc`).
> Replace karma-coverage

- CHANGELOG.md
- doc/troubleshooting.md
- lib/run-process.js
Node's child process .spawn is unable to invoke batch files on Windows without a shell.  This prevents the CLI from invoking Mocha.  This fix enables spawn's .shell option.
> STCLI-89 spawn on windows

- CHANGELOG.md
- lib/test/nightmare-service.js
- package.json
- test/test/nightmare-service.spec.js
This replaces the CLI's use of ui-testing (framework-only branch) with stripes-testing.
> STCLI-92 stripes testing

- CHANGELOG.md
- lib/environment/inventory.js
- lib/test/nightmare-service.js
This includes platforms in the logic that generates the --run option for ui-testing's test-module.js.  Previously invoking a child platform's tests (such as platform-core's tests inside of platform-complete) was not possible because the CLI would handle them like local tests and apply the current working directory.  Now a platform's test script can be invoke the same way an app is handled via --run.
> STCLI-100 include platforms in --run logic

- package.json
Looks like this change: https://github.com/webpack-contrib/karma-webpack/pull/336 broke something in the way our test index gets defined. Karma then wouldn't find any tests to run.
This should get us back to a stable state.
> Pin karma-webpack to 3.0.0

- CHANGELOG.md
- lib/commands/serve.js
Discovered when trying to `stripes serve` the `ui-organization` module, which only contains settings. `stripes serve` worked, it just logged out a warning.
> Allow serve for settings modules

- package.json
Resolves
```
warning webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new
features!
```
> Upgrade webpack-bundle-analyzer

- CHANGELOG.md
- lib/cli/context.js
- test/cli/context.spec.js
Recently added `isPlatform` logic was dependent on the `stripes.type` property used by ui modules.  However, platforms don't currently define `stripes` property their package.json.  (Perhaps they should?)
This fix sets isPlatform at the same time context.type is assigned "platform", allowing existing checks for `context.type === 'platform'` to migrate to `context.isPlatform`.
> STCLI-104 isPlatform fix

- CHANGELOG.md
- resources/ui-app/package.json
Semantic versioning treats caret deps on versions with leading 0s like
tilde deps, i.e. only the patch version can change. Starting all apps
and libraries at v1.0.0 instead of v0.1.0 avoids the confusion and pain
that otherwise results from bumping the minor version of a v0.x.y
module and finding that it isn't being pulled in as anticipated.
Fixes [STCLI-105](https://issues.folio.org/browse/STCLI-105)
> start new apps at v1.0.0

- CHANGELOG.md
- lib/commands/perm/create.js
- lib/okapi/module-service.js
- lib/okapi/okapi-repository.js
Stripes CLI provides an easy way to create new permissions for ui-modules with `stripes perm create`.  The new permission can be optionally assigned to a user with `--assign` at the same time.
However, if the module is not already enabled for a tenant, this optional step fails.  By calling into existing `mod enable` logic, we can ensure the module is enabled for the tenant before assigning the newly created permission to a user.
Another issue was uncovered in that outdated method names were still referenced from within `updateModuleDescriptor()` to enable/disable modules.
Fixes STCLI-106
> STCLI-106 Ensure module is enabled before assigning permission

- CHANGELOG.md
- lib/cli/context.js
- test/cli/context.spec.js
This enables the CLI to serve/test from within more stripes-* module directories.  Basing `isStripesModule` on the CLI's `stripesModules` inventory helps to ensure consistency.
Next steps: Review the various context checks within the CLI and consider relaxing or revoking them.  Not all may be necessary and and in fact a few have proven to interfere as observed here and in STLI-78.
> Expand isStripesModule logic

- CHANGELOG.md
- package.json
- resources/platform/package.json
- resources/ui-app/package.json
Unblocks https://github.com/folio-org/stripes-core/pull/426
After merge, will create tag and publish to https://repository.folio.org/repository/npm-folio/.
> Release v.1.5.0

- CHANGELOG.md
- lib/commands/test/karma.js
- lib/test/webpack-config.js
Discovered during long `ui-eholdings` test runs that were causing browser crashes.
Thanks @wwilsman for the fix.
> Remove HMR plugin during Karma tests

- lib/create-app.js
- resources/ui-app/CHANGELOG.md
Concerning [STCLI-67](https://issues.folio.org/browse/STCLI-67), the template for generating app-module should be updated due to lokalize.co restrictions, so that, the language files should be moved to new path `translations/<ui-app-name>/en.json`. 
For example, in case of ui-users the language files (`translations/en.json`) should move to `translations/ui-users/en.json`.
Therefore, the stripes-translations-plugin must look for translations in both translations/ and translations/moduleName.
- using [copy](translations/<ui-app-name>/en.json.) add option 'move', that allows to rename files.
> STCLI-67: Update app module template with new translation directory

- CHANGELOG.md
- lib/cli/stripes-core.js
- lib/okapi/module-service.js
- resources/ui-app/CHANGELOG.md
This imports the stripes-core dependencies responsible for locating stripes-* modules via the CLI's stripes-core API wrapper.  Doing so ensures the version of stripes-core used for building a platform is the same version used for generating module descriptors for the platform.  Fixes STCLI-111.
> STCLI-111 stripes-core deps

- CHANGELOG.md
- doc/commands.md
- doc/generator.js
- lib/commands/common-options.js
- lib/commands/mod/add.js
- lib/commands/mod/descriptor.js
- lib/commands/mod/disable.js
- lib/commands/mod/enable.js
- lib/commands/mod/install.js
- lib/commands/mod/list.js
- lib/commands/mod/pull.js
- lib/commands/mod/remove.js
- lib/commands/mod/update.js
- lib/commands/mod/view.js
- lib/commands/perm/assign.js
- lib/commands/perm/unassign.js
- lib/commands/platform/backend.js
- lib/environment/inventory.js
- lib/okapi/module-service.js
- lib/okapi/okapi-repository.js
This introduces a new `platform backend` command to facilitate the deployment, enabling, and upgrading of back-end modules in a Vagrant box needed to support a front-end FOLIO platform.  STCLI-15
> STCLI-15 setup backend for platform

- lib/stripes-cli.js
This reverts commit 2214bc9f6dd137a9639ed2bca1cdc1b7aef4c682.
> Revert "Declare script name for consistent help output"

- lib/environment/inventory.js
One of the nuances to yarn workspaces is despite installing devDependencies, they fail to run npm lifecycle scripts like `prepublish` that run at the time of a local install, so linked dependencies within the workspace aren't properly built like they would be if one were using an aliased directory outside of the workspace. 
Since
* this isn't common knowledge
* this can be really inconvenient
* `stripes-react-hotkeys` doesn't require an extreme amount of maintenance
Best to just exclude it from the options.
> Remove `stripes-react-hotkeys` option

- CHANGELOG.md
- doc/backend-guide.md
- doc/commands.md
- lib/cli/stdin-handler.js
- lib/commands/mod/filter.js
- lib/commands/mod/install.js
- lib/okapi/module-service.js
This adds support to consume `mod install` simulate output as input for subsequent calls to `mod install`.  This change, along with a new `mod filter` command, enables the CLI to be used to follow along with the single-server install instructions.  A new CLI back-end guide has been drafted to demonstrate usage.
Refs STCLI-15
> STCLI-116 json input

- CHANGELOG.md
- lib/environment/development.js
This uses the correct relative path for loading the CLI's own package.json in the `workspace` command.
> STCLI-121 use correct relative path

- CHANGELOG.md
- resources/ui-app/src/index.js
- resources/ui-app/src/routes/example-page.js
- resources/ui-app/test/bigtest/network/config.js
- resources/ui-app/translations/en.json
According to [STCLI-98](https://issues.folio.org/browse/STCLI-98), a working demonstration of how to make Okapi API requests should be added to ui-app template.
`ExamplePage` component now has `manifest` static property, which includes  `_/discovery/health` endpoint used for requesting data from the back-end. The obtained data is processed by the component methods and displayed. Appropriate mirage mock is added
> STCLI-98: add sample API request to ui-app template

- CHANGELOG.md
- resources/workspace/package.json
Specifying an exact version of the CLI in the workspace template prevents Yarn from resolving that dependency when targeting `npm-folioci`.  This is because the `npm-folioci` registry uses inflated patch numbers and therefore does not offer an exact `1.7.0` version, for example.  By re-applying the caret `^` version range lost in a prior commit, we restore the ability to use the `stripes workspace` command while targeting `npm-folioci`.
> STCLI-123 use caret version

- CHANGELOG.md
- lib/environment/inventory.js
folio-testing-platform has been deprecated in favor of using the platform-complete snapshot branch.  The platform reflects a pre-stripes-framework state and therefore could cause issues if used as-is.  Also fixes FOLIO-1370
> Remove folio-testing-platform

- CHANGELOG.md
- doc/commands.md
- lib/stripes-cli.js
- package.json
This upgrades Yargs to 12.x offering new features and fixes.  For example, the ability to use `.completion()` with `.recommendCommands()` has been fixed (previously removed in https://github.com/folio-org/stripes-cli/commit/d2ebf2e2493f8e5a69c2db4c8798669c44f2ba41) and support for middleware added (referenced in STCLI-99).
> Upgrade yargs

- CHANGELOG.md
- doc/commands.md
- lib/commands/workspace.js
- lib/environment/development.js
This option has been removed from the workspace command rather than fixed because a workspace containing all possible modules is discouraged. If necessary, the interactive input still supports selection of all.
> STCLI-83 remove "--modules all"

- CHANGELOG.md
- lib/test/karma-service.js
This issue was likely caused by the upgrade to Yargs which introduced a difference in handling of unset command-line options.
> STCLI-124 guard against unset karma options

- doc/user-guide.md
The "all" option has since been removed
> Remove reference to --modules all in guide

- CHANGELOG.md
- package.json
There are no breaking changes related to the build/serve API exposed by stripes-core in version 3.x, therefore the CLI will continue to work with either major version.  This should ease transition for folks who happen to update the CLI independent of stripes-core or stripes framework.
> Add support for stripes-core 3.x

- CHANGELOG.md
- doc/commands.md
- lib/commands/mod/descriptor.js
- lib/okapi/descriptor-service.js
This adds support for writing module descriptors to files.  Writing to files triggered by a new `--output` option on the existing `mod descriptor` command.  With this functionality, we will be able to retire the `build-module-descriptors.js` script currently duplicated within in each platform.
> STCLI-125 descriptor files

- README.md
- doc/backend-guide.md
- doc/commands.md
- lib/commands/mod/discover.js
- lib/okapi/discovery-service.js
- package.json
- test/okapi/discovery-service.spec.js
This wraps up STCLI-114 with updated documentation referencing the new `snapshot-backend-core` VMs. New support has been added to`mod discover` to use the VM's default NAT gateway [described here](https://github.com/folio-org/folio-ansible/blob/7d2137478ce92cec56ab33e35b89ea403548b6ee/doc/index.md#running-backend-modules-on-your-host-system) when registering a locally hosted back-end module with the VM.
> STCLI-114 follow-up

- doc/commands.md
- lib/commands/build.js
This includes `--no-minify` in CLI documentation. This is a feature that has been in place for quite some time and works because the CLI will pass the `--no-minify` option to stripes-core (where it has been implemented).  However, the option's existence was never surfaced in the CLI help docs.
> STCLI-96 --no-minify

- CHANGELOG.md
- lib/cli/context.js
- lib/commands/app/bigtest.js
- lib/commands/app/create.js
- lib/commands/app/perms.js
- lib/commands/perm/create.js
- lib/commands/platform/clean.js
- lib/commands/platform/install.js
- lib/commands/platform/pull.js
- lib/commands/status.js
- lib/commands/test/nightmare.js
- lib/commands/workspace.js
- lib/environment/development.js
- test/cli/context.spec.js
- test/commands/app/create.spec.js
This refactor replaces remaining usages of `context.type` with boolean flags.  The test for "app" in particular has proven troublesome in the past as many UI modules are actually reported as "settings" or "plugin".  Checks for "app" would then fail for those modules.  Work had previously begun to replace `context.type === 'app'` with a new `context.isUiModule` boolean.  This PR completes that work for remaining usages and the other strings like "platform".
Well, there is one remaining usage, `context.type == 'components'`, which is an outlier that will be addressed by STCLI-107 and will need coordination with some `stripes-` repos.
> STCLI-78 replace context.type

- CHANGELOG.md
- doc/backend-guide.md
- doc/commands.md
- lib/commands/perm/filter.js
- lib/commands/platform/backend.js
- lib/okapi/permission-service.js
- test/okapi/permission-service.spec.js
By exposing the filtering logic from `platform backend` as its own command, the individual steps outlined in the backend-guide can be performed without unnecessary permission calls.
> STCLI-126 perm filter

- lib/commands/test.js
- lib/commands/test/karma.js
- lib/commands/test/nightmare.js
This is a quick fix to see if it resolves a testing issue on Jenkins.  A more complete solution will follow.
> Don't check stdin for a config file when running tests

- CHANGELOG.md
- doc/commands.md
- lib/cli/prompt-middleware.js
- lib/cli/stdin.js
- lib/commands/test.js
- lib/commands/test/karma.js
- lib/commands/test/nightmare.js
This adds a check for TTY before attempting to call getStdin().  Without TTY, the call would hang resulting in FOLIO-1807.  The previous quick fix has been rolled back as its no longer needed.  That fix manually disabled the getStdin() call for selected commands, whereas this solution handles it automatically for any command based on the presence of TTY.
> STCLI-131 check tty

- CHANGELOG.md
- doc/commands.md
- lib/commands/test/nightmare.js
- lib/test/nightmare-service.js
- package.json
This allows the CLI to pass the `--reporter` option to Mocha when running Nightmare integration tests.  The `mocha-jenkins-reporter` has been made available as well.
> STCLI-84 mocha reporter option

- doc/commands.md
- lib/commands/common-options.js
- lib/commands/serve.js
The CLI defines some build/serve options that are not currently implemented in stripes-core.  These options have been removed and the documentation regenerated to avoid confusion.
> STCLI-132 serve doc corrections

- resources/ui-app/README.md
In the "ui-app" template, use the current year as the initial year of creation [FOLIO-360](https://issues.folio.org/browse/FOLIO-360) (thereafter use range of years).
Perhaps this could be automated.
> FOLIO-360 Use current initial year of creation in template

- doc/commands.md
- lib/commands/common-options.js
- lib/commands/okapi/pathDelete.js
- lib/commands/okapi/pathGet.js
- lib/commands/okapi/pathPost.js
- lib/commands/okapi/pathPut.js
- lib/okapi/endpoint-service.js
Following through on [this Slack thread](https://folio-project.slack.com/archives/C210RP0T1/p1553879215109100) and the [subsequent JIRA issue](https://issues.folio.org/browse/STCLI-135).
First time mucking around in the guts of stripes-cli, so feel free to be exhaustive with any issues in this PR.
One thing that I wasn't sure about was using the `stdinJsonMiddleware` over the `stdinStringMiddleware` for the POST/PUT body. I went with JSON because most use cases of POST/PUT will be for JSON content and the backend complains if I just throw the text I get from `stdinStringMiddleware` at it.
> STCLI-135 Added Okapi path accessor commands

- CHANGELOG.md
- package.json
On windows 10, Node LTS, the workspace command hangs after module selection.
If modules are explicitly provided to the command via the `--modules` parameter, it pulls the modules and proceeds as expected.
> upgrade inquirer dependency to latest release.

- CHANGELOG.md
- doc/user-guide.md
The changelog was out of sync with a nice new feature included in v1.11 that allows issuing GET, POST, PUT, and DELETE requests to arbitrary Okapi endpoints using Stripes CLI.  While the command reference was current, I've added a brief mention of this feature in the user guide under "Interacting with Okapi" to help surface this new handy capability.
> Sync changelog

- CHANGELOG.md
- lib/environment/inventory.js
- package.json
ui-tenant-settings will replace ui-organization (ui-vendors is being
renamed to ui-organizations and that seemed confusing). Including it
here makes it available to stripes-testing as a module potentially
containing integration tests.
Refs [UIORG-156](https://issues.folio.org/browse/UIORG-156)
> include tenant-settings in module list

- CHANGELOG.md
- package.json
GitHub reports a security vulnerability in webpack-bundle-analyzer,
WS-2019-0058.
> upgrade dep to avoid vulnerability

- CHANGELOG.md
- lib/cli/context.js
- lib/commands/status.js
- lib/environment/inventory.js
- test/cli/context.spec.js
Various commands that need to be executed from within a UI module (eg, `stripes mod add`) don't work if the UI module uses `stripes.actsAs` instead of `stripes.type`.
I've attempted here to use `actsAs` first and fallback to `type`. No instances of `context.type` usage jumped out to me as being immediately rewritable since most of these checks do in fact nicely use `isUiModule`.
Added a couple of tests to ensure we're pulling the correct info.
Also added an entry to the `inventory` for the module that set me down this path.
> Added handling for actsAs in module type check

- CHANGELOG.md
- package.json
stripes-testing `v1.6.0` includes `checkout`, `setCirculationRules`
helpers.
> depend on stripes-testing v1.6.0

- lib/environment/inventory.js
since it has been deprecated in favor of ui-app-template
> Removed ui-trivial

- CHANGELOG.md
- doc/commands.md
- lib/commands/platform/clean.js
- Fulfills https://issues.folio.org/browse/STCLI-130
- Added optional param `--removeLock` to delete yarn.lock file(s) after cleaning and prior to re-install.
> Stcli 130 remove yarn lock files on platform clean

- package.json
https://issues.folio.org/browse/STCLI-143
##Purpose
Package "nyc@^12.0.2" uses "mem@^1.1.1". In "mem" before version 4.0.0, there is a memory leak due to old results not being removed from the cache despite reaching maxAge. Bumping up the version of "nyc" package to 14 fixes this issue as it uses "mem@4.3.0"
> STCLI-143: bump up nyc version

- lib/environment/inventory.js
Add [ui-data-export](https://github.com/folio-org/ui-data-export) module in the scope of the [UIDEXP-8](https://issues.folio.org/browse/UIDEXP-8).
> UIDEXP-8: Add ui-data-export module

- lib/environment/inventory.js
Add [stripes-data-transfer-components](https://github.com/folio-org/ui-data-export) module in the scope of the [UIDEXP-11](https://issues.folio.org/browse/UIDEXP-11).
> UIDEXP-11: Add stripes-data-transfer-components module

- CHANGELOG.md
- lib/cli/generate-module-descriptor.js
- test/okapi/descriptor-service.spec.js
Includes test coverage.
This is the second and last Stripes parts of OKAPI-509, and allows a UI module to declare optional dependencies on Okapi interfaces.
(The first Stripes part was an analogous change in the deprecated-but-still-used package2md script: see https://github.com/folio-org/stripes-core/commit/358342c2c2e63bcceaeae5b8c5b68a850d2afdcd)
> Extend 'stripes mod generate --full --strict' to support optionalOkapiInterfaces

- CHANGELOG.md
- doc/commands.md
- doc/user-guide.md
- lib/commands/build.js
- test/commands/build.spec.js
- Fulfills [STCLI-95](https://issues.folio.org/browse/STCLI-95).
- Updated documentation for `--output` usage and default value when omitted.
- Updated`commands/build.js` to support injecting `stripesPlatform` and `stripesCore` so they can be mocked. 
- Added unit tests for new usage.
> Add default output path to build command

- package.json
We added support for `stripes-core` `v5`; we need to allow UI apps to
specify that.
> bump minor to 1.16

- CHANGELOG.md
- package.json
Includes new command `stripes inventory --fetch` to update module list for `stripes workspace` command. Refs STCLI-122.
> Releasing 1.17.0

- CHANGELOG.md
- lib/okapi/okapi-client.js
Alter the logging output from okapi-client, which is present when
invoked with `DEBUG=stripes-cli:okapi`, so it includes HTTP request
headers and body in the format of `curl` commands. Having this
`under-the-hood`/`behind-the-curtain` view could make debugging these
commands much easier.
> okapi-client logs as curl commands

- lib/cli/context.js
@K-Felk is currently running into an issue when trying to run tests with a `handler` module. This PR  adds a `handler` type to the list of ui modules so: https://github.com/folio-org/stripes-cli/blob/160ab87f34b5caef7aba257d158e6a6f00a1ee50/lib/commands/test/karma.js#L17 doesn't complain about it.
> Add handler to ui module list

- CHANGELOG.md
- package.json
Fulfills [STCLI-146](https://issues.folio.org/browse/STCLI-146)
Noting that only breaking change is deprecating Node 6, which we don't rely on (we are generally on 8 or higher): https://github.com/karma-runner/karma/releases/tag/v4.0.0
Using 4.4, since that also quietly removed the `core-js` dependency: https://github.com/karma-runner/karma/releases/tag/v4.4.0
> Updating to karma 4.4

- CHANGELOG.md
- doc/commands.md
- doc/user-guide.md
- lib/commands/build.js
- Add support for building and consuming Webpack DLLs. Refs [STCLI-154](https://issues.folio.org/browse/STCLI-154).
- Updated documentation.
- See Stripes Core PR here: https://github.com/folio-org/stripes-core/pull/945
> Webpack DLL Support

- CHANGELOG.md
- Jenkinsfile
- package.json
Include support for `@folio/stripes-core` `7.0.0`.
> support stripes-core v7

- lib/cli/stripes-core.js
- package.json
https://issues.folio.org/browse/STRIPES-730
This is an attempt to break up a dependency on stripes-core by introducing [stripes-webpack](https://github.com/folio-org/stripes-webpack).
There is a corresponding PR in stripes-core related to this work:
https://github.com/folio-org/stripes-core/pull/1003
This change looked pretty straightforward (at least from the stripes-cli point of view) but perhaps I'm still missing something here. If this looks good I think we should probably rename `StripesCore` class to something else.
> STRIPES-730: Break up stripes-cli and stripes-core

- CHANGELOG.md
- lib/cli/stripes-core.js
- package.json
Webpack config has been moved to `stripes-webpack` out of `stripes-core`. This PR is switching to stripes-webpack.
> STCLI-167: Use stripes-webpack instead of stripes-core

- CHANGELOG.md
- package.json
For some users, `stripes-webpack` `^1.2.0` causes test failures that are
not present in `1.1.0`. It is not clear how these failures are related
as they do not occur for all users. It may be a `yarn` problem, or
something else environmental that we haven't sussed out yet. The errors
look like
```
...
ERROR in ./test/bigtest/tests/instance-edit-page-test.js
Module not found: Error: Can't resolve 'react/jsx-runtime' in '/Users/zburke/temp/ui-inventory/test/bigtest/tests'
@ ./test/bigtest/tests/instance-edit-page-test.js 15:0-48 28:28-32
@ ./test/bigtest/tests sync -test
@ ./test/bigtest/index.js
ℹ ｢wdm｣: Failed to compile.
19 04 2021 11:38:30.042:WARN [karma]: No captured browser, open http://localhost:9876/
19 04 2021 11:38:30.047:INFO [karma-server]: Karma v4.4.1 server started at …
```
> STCLI-176 pin stripes-webpack to ~1.1.0

- package.json
We were using a rather old version... 5.2.0... 😨 This moves us to ^8.3.0
> upgrade mocha

- CHANGELOG.md
- package.json
Bump `@folio/stripes-webpack` to reduce build warnings and allow
transpilation of modules outside the `@folio` namespace.
> bump @folio/stripes-webpack to 1.3.0

- CHANGELOG.md
- package.json
so that @octokit/core > 3 peerDependency could be resolved. Refs [STCLI-178](https://issues.folio.org/browse/STCLI-178)
Based on breaking changes listed here: https://github.com/octokit/rest.js/releases/tag/v18.0.0, confirmed we are in the clear since our usage is low: https://github.com/folio-org/stripes-cli/blob/54d179bd43af73a4b4eef8ed8e5611cbc4af8e6d/lib/environment/inventory.js#L37
Confirmed correct behavior with `stripes workspace` command.
> STCLI-178 Updated @octokit/rest

- CHANGELOG.md
- index.js
- lib/environment/inventory.js
- package.json
Re-export the babel config options import from `@folio/stripes-webpack`
so that modules needing access to it for Jest/RTL testing do not need to
maintain their own local copies.
Refs [STCLI-182](https://issues.folio.org/browse/STCLI-182)
> STCLI-182 re-export babel options from stripes-webpack

- CHANGELOG.md
- index.js
`babelConfig` is not exported from `stripes-webpack`, [`babelOptions` is](https://github.com/folio-org/stripes-webpack/blob/56188f6ddffafab7d80ce53e9f36987297dd3e24/index.js#L3).
Re-export that one.
Corrects the typo in #265 that made it into a do-nothing PR.
Refs [STCLI-182](https://issues.folio.org/browse/STCLI-182)
> STCLI-182 export babelOptions, not babelConfig

- CHANGELOG.md
- lib/commands/test/karma.js
- lib/test/webpack-config.js
- package.json
Since stripes-components IS the dependency that the new webpack aliases reference, they won't resolve in CI for stripes-components - so they were failing when the webpack configuration was processed - which meant a dead test suite...
Needed to conditionally omit the webpack aliases for shared styles when running from an isolated clone of stripes-components - so I passed stripes-cli context into a function that would inject the new aliases into the webpack dev configuration in non stripes-components cases.
The history:
Upgrading the stripes postcss stack...was many multiple breaking versions behind...
Upgraded CSS-loader left with unresolved imports.
CSS-loader's proposed fix: webpack aliases
Conditional logic needed for injecting the aliases (this PR)
PR in …
> STCLI-183 Storybook 6 - stripes-components special case for style aliases.

- CHANGELOG.md
- lib/test/karma-service.js
- package.json
- test/test/karma-service.spec.js
https://issues.folio.org/browse/STCLI-187
There is a corresponding PR in stripes-webpack https://github.com/folio-org/stripes-webpack/pull/36 which will need to be merged first in order for this one to pass.
> STCLI-187: Update webpack to v5

- CHANGELOG.md
- package.json
Avoid the sabotaged `colors` module by adding a dev-dep on the
last-known-good build, `1.4.0`. Using a dev-dep, even though `colors` is
technically only a transitive dep, allows both `yarn` and `npm` to
handle this change. In yarn-land, arguably a `resolutions` entry would
be more correct, but that would only work in yarn-land.
Refs [STCLI-188](https://issues.folio.org/browse/STCLI-188)
> STCLI-188 avoid sabotaged colors

- package.json
`@folio/stripes-webpack` published `v3.0.3` to avoid bugs in a
dependency (https://github.com/cerner/terra-toolkit/issues/730) so we
need to set `v3.0.3` as the minimum version here.
> avoid buggy transitive deps from @folio/stripes-webpack

- CHANGELOG.md
- package.json
A breaking change to node compatibilty for `isBinaryFile`, a transitive
dependency via `karma`, was published in a patch release. It isn't clear
if the author doesn't understand semantic versioning or just doesn't
care about it, but multiple pleas to move the changes to a new major
version and publish a patch to restore compatibility in the 4.0.x line
were rebuffed (https://github.com/gjtorikian/isBinaryFile/issues/51).
Refs [STCLI-193](https://issues.folio.org/browse/STCLI-193)
> STCLI-193 avoid sabotaged isBinaryFile

- CHANGELOG.md
- package.json
`webpack` `5.69.0` and `5.70.1` introduced changes to "handle multiple
alternative directories (e. g. due to resolve.alias or resolve.modules)
when creating an context module" that appear to be incompatible with the
way moment handles dynamic loading of locales. That change was reverted
in `5.69.1` and then re-applied in `5.70.0`, hence the choice of
`5.69.1` here.
Honestly, the details are fuzzy but the incompatibility (in the form of
~7k lines of warnings) is indisputable. I believe the issue is captured
by https://github.com/moment/moment/issues/5492. It feels like `moment`
was built in a pre-ESM world and just can't cope with how things have
evolved since.
Refs [STCLI-195](https://issues.folio.org/browse/STCLI-195)
> STCLI-195 avoid webpack > 5.69.1

- CHANGELOG.md
- package.json
Oy, the hits just keep coming. It seems that `5.69.0` and `5.70.0` don't
play nice with `moment` and barf thousands of lines of warnings into the
log when running tests, but `5.69.1` isn't compatible with
`karma-webpack` which prevents tests from running _at all_. Yuck.
Sample build output: 
```
$ stripes test karma --karma.singleRun --karma.browsers ChromeDocker --karma.reporters mocha junit --coverage
Starting Karma tests...
01 04 [20](https://github.com/folio-org/stripes-core/runs/5789164817?check_suite_focus=true#step:13:20)[22](https://github.com/folio-org/stripes-core/runs/5789164817?check_suite_focus=true#step:13:22) 14:07:[29](https://github.com/folio-org/stripes-core/runs/5789164817?check_suite_focus=true#step:13:29).960:ERROR [plugin]: Cannot find plugin "karma-webpack".
Did you …
```
> STCLI-195 pin webpack to ~5.68.0

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
Update Node to active LTS; v12 is past EOL.
Refs [STCLI-208](https://issues.folio.org/browse/STCLI-208), [FOLIO-3432](https://issues.folio.org/browse/FOLIO-3432)
> STCLI-208 update NodeJS to Active LTS, v16

- CHANGELOG.md
- doc/commands.md
- lib/commands/build.js
- lib/commands/common-options.js
- lib/commands/serve.js
- lib/webpack-common.js
- test/commands/build.spec.js
- test/webpack-common.spec.js
Webpack caches build output by default. Most of the time, that's what we
want, so that's good. But sometimes it isn't what we want, and we need
an easy way to turn it off, so now there's `--cache false` for that.
Refs [STCLI-209](https://issues.folio.org/browse/STCLI-209)
> STCLI-209 provide "--cache false" to disable webpack cache

- lib/commands/test/karma.js
- lib/test/karma-service.js
The --watch and --cache options implemented in #290 added keys with `undefined` to the configuration object provided to webpack. These options would evaluate to `false`, so they would not effectively turn on the corresponding feature.
> STCLI-198 correctly implement caching, watching (default to true when CLI flags are absent)

- lib/test/webpack-config.js
The recent changes in: https://github.com/folio-org/stripes-webpack/pull/63 changed the signature of the `webpack.config.cli.dev`. The configuration used to export a config (an object) but now it's a function so we need to adjust it here in stripes-cli.
https://issues.folio.org/browse/STCLI-211
> STCLI-211: consume webpack.config.cli.dev as a function

- CHANGELOG.md
- lib/commands/build.js
- package.json
- Fixes [STCLI-165](https://issues.folio.org/browse/STCLI-165)
- Bug was first introduced by [STCLI-95](https://issues.folio.org/browse/STCLI-95)
- Verified against `platform-core` with command `yarn stripes build stripes.config.js ./rb-test`
> Fix bug outputPath positional is ignored on build command

- CHANGELOG.md
- lib/commands/test/karma.js
- lib/test/karma-service.js
https://issues.folio.org/browse/STCLI-220
This PR turns off `exprContextCritical` when karma/bigtest tests are running to avoid warnings similar to:
````js
WARNING in ./node_modules/mocha/mocha-es2018.js 18541:26-55
Critical dependency: the request of a dependency is an expression
@ ./node_modules/@bigtest/mocha/dist/esm/index.js 1:0-75 3:22-30 5:20-26 7:24-34 9:19-24 11:23-32 13:16-18
@ ./test/bigtest/tests/about-test.js 14:0-58 20:0-8 52:2-10 53:4-14 56:4-6
@ ./test/bigtest/tests/ sync -test ./about-test.js ./about-test
@ ./test/bigtest/index.js 10:18-60
````
It also sets webpack mode to `none` to avoid warnings similar to:
````js
WARNING in DefinePlugin
Conflicting values for 'process.env.NODE_ENV'
````
> STCLI-220: Adjust webpack config for karma to avoid warnings

- package.json
`stripes-webpack` >= `4.2.0` looks for its entrypoint in `stripes-ui` instead of `stripes-core`, where it look up until `stripes` `8.0.0`. In order to remain capable of building platforms based on `< 8.0.0`, `stripes-cli` must therefore lock onto `stripes-webpack` `~4.1`.
Refs [STCLI-227](https://github.com/folio-org/stripes-cli/pull/new/STCLI-227)
> STCLI-227 lock stripes-webpack for stripes v7 compat

- lib/test/webpack-config.js
This is a small fix related to transpilation work done in:
https://github.com/folio-org/stripes-webpack/pull/73
The path to shared styles has changed from `webpack.config.cli.dev.shared.styles` => `webpack.config.cli.shared.styles`
This PR is addressing it.
> STCLI-224: Adjust path to shared styles

- CHANGELOG.md
- package.json
We pinned webpack in [STCLI-195](https://issues.folio.org/browse/STCLI-195) but the build errors we encountered at that time have abated.
Refs [STCLI-222](https://issues.folio.org/browse/STCLI-222)
> STCLI-222 unpin webpack dependency

- CHANGELOG.md
- lib/stripes-cli.js
- package.json
[`update-notifier`](https://github.com/yeoman/update-notifier) has shifted to pure-ESM but stripes-cli is still CJS. Eventually, we'll have to migrate as well, but for now we can just load `update-notifier` asynchronously.
> Bump update-notifier to 6.0.2

- CHANGELOG.md
- package.json
- test/test-setup.spec.js
Bump [`sinon`](https://github.com/sinonjs/sinon) from `4.1.4` to `15.0.4`. Breaking changes in sinon are not well-documented, even though `CHANGES.md` catalogs many new major versions. Given this is only a dev-dep and our tests still run with just a minor tweak, this implies that whatever surfaces _did_ change between versions 4 and 15 are not surfaces that we touched. Whew. 
Bump its companion [`sinon-chai`](https://github.com/domenic/sinon-chai) from `2.14.0` to `3.7.0`. The only breaking change here was in raising the minimum versions of node, sinon, and chai to versions we already require.
> Bump sinon to 15.0.4, sinon-chai to 3.7.0

- lib/test/webpack-config.js
- lib/webpack-common.js
https://issues.folio.org/browse/STCLI-231
This was already fixed for bigtest tests in: https://github.com/folio-org/stripes-cli/pull/313
But I missed the fact that the same functionality is used for cypress tests.
> STCLI-231: Adjust finding  in webpack config in order to fix coverage

- CHANGELOG.md
- package.json
Bump `stripes-webpack` to `~4.2.1` to include babel plugins that are no longer part of `@babel/preset-env`.
Refs [STRWEB-86](https://issues.folio.org/browse/STRWEB-86)
> Bump `stripes-webpack` to 4.2.1

- CHANGELOG.md
- package.json
*BREAKING* Bump `@folio/stripes-webpack` to v5. stripes-cli re-exports portions of stripes-webpack and, from the point of view of applications with dev-deps on stripes-cli, represents the public API for stripes-webpack. Thus, even though stripes-webpack is a direct (and thus internal) dependency here, it functions more like a peer-dependency and since that version is changing, then this one must too.
Refs [STCLI-235](https://issues.folio.org/browse/STCLI-235)
> STCLI-235 update stripes-webpack to v5

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
In CI, bump the NodeJS version from 16 to 18.
Refs [STCLI-236](https://issues.folio.org/browse/STCLI-236)
> STCLI-236 use NodeJS v18 in CI builds

- CHANGELOG.md
- lib/cli/context.js
- lib/cli/global-dirs.js
- lib/cli/stripes-config-middleware.js
- lib/commands/mod/install.js
- lib/commands/translate/compile.js
- lib/create-app.js
- lib/stripes-cli.js
- lib/test/setup-bigtest.js
Log errors before throwing a simplified message. This detail facilitates debugging while still providing a user-friendly error message.
Refs [STCLI-240](https://issues.folio.org/browse/STCLI-240)
> STCLI-240 thoroughly log errors

- CHANGELOG.md
- doc/commands.md
- lib/commands/common-options.js
- lib/commands/serve.js
- lib/platform/tenant-config.js
- lib/run-proxy.js
- package.json
After updates that involve using Cookies for authentication, developers could face issues that cookies wouldn’t be included in requests
Browsers refused to set cookies due to “SameSite=”Lax” attribute:
Since this is a browser limitation we can overcome this by setting up a local proxy server which would redirect requests to Okapi and back.
This server is included as part of stripes-cli, so that developers don't have to install any third-party software.
Added two new options to `serve` command:
- `--startProxy`
- `--proxyPort`
https://github.com/folio-org/stripes-cli/assets/19309423/d1512568-55d6-43b9-b435-27b615675bcb
[STCLI-246](https://folio-org.atlassian.net/browse/STCLI-246)
> STCLI-246 Add a proxy server to overcome issues with cookies SameSite policy.

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
Hahaha don't do anything related to STRIPES-924, which is The Right Way to fix this problem, but instead just work around it by bumping the version of the deprecated dep, because that's a smaller/safer operation on a Friday afternoon.
Doesn't actually ref [STRIPES-924](https://folio-org.atlassian.net/browse/STRIPES-924), just pokes it in the eye
> STRIPES-924 use valid upload-artifact version

- doc/commands.md
- lib/commands/common-options.js
- lib/commands/serve.js
- lib/run-proxy.js
Use case, per @kaladay: 
* This allows a workstation with a static IP to (a) serve as the proxy and (b) host the corresponding bundle for a third party, e.g. a demo machine in another room, a colleague in another office
> Use --proxyUrl to allow control over the scheme, host, and port

- doc/commands.md
- lib/commands/common-options.js
- lib/commands/serve.js
- lib/run-proxy.js
There are two features here:
1. provide new CLI option `--proxyUrl` to allow use of a hostname other than localhost, allowing the machine hosting the bundle to be accessed remotely (e.g. from a conference room, or by a colleague in another office, etc etc)
2. overwrite CORS headers between the proxy and browser, satisfying the browser that CORS requirements are being met (shhhhh) 
Details on Part 2: 
Overwrite the following CORS headers between the proxy and browser: 
```
Access-Control-Allow-Origin: http://localhost:${PORT}
Access-Control-Allow-Credentials: true
```
The ACAO value is commonly set to `*` for un-credentialed requests (i.e. those without cookies), but as [MDN docs for CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) notes:
> When responding to a [credentialed …
> STCLI-247 overwrite CORS headers in proxy responses

- .github/workflows/ui.yml
There is no module descriptor here.
Refs [STCLI-251](https://folio-org.atlassian.net/browse/STCLI-251), [STRIPES-938](https://folio-org.atlassian.net/browse/STRIPES-938)
> STCLI-251 GA: Omit publishing MD

- CHANGELOG.md
- lib/platform/tenant-config.js
`<StrictMode>` is intended to be a development-only setting so it should be disabled when running tests. e.g. a component that fetches data on mount with `accumulate: true` would see that data duplicated.
Refs [STCLI-256](https://folio-org.atlassian.net/browse/STCLI-256)
> STCLI-256 turn off StrictMode when running tests

- .github/CODEOWNERS
Refs [STCLI-257](https://folio-org.atlassian.net/browse/STCLI-257)
> STCLI-257 implement CODEOWNERS

- CHANGELOG.md
- lib/commands/platform/pull.js
Since a few of UI modules are now using `main` instead of `master` branch we should update the pull command to check for it also.
[STCLI-258](https://folio-org.atlassian.net/browse/STCLI-258)
> STCLI-258 Check for `main` branch in `stripes platform pull` command.

- CHANGELOG.md
- package.json
* `@formatjs/cli` to `^6.6.0`
* `@formatjs/cli-lib` to `^7.3.0`
Refs [STCLI-262](https://folio-org.atlassian.net/browse/STCLI-262)
> STCLI-262 upgrade @formatjs/cli packages

- CHANGELOG.md
- package.json
* Upgrade `@folio/eslint-config-stripes` to `v8.0.0` in order to provide consistent dependencies.
> bump @folio/eslint-config-stripes to v8.0.0

- CHANGELOG.md
- package.json
This reverts commit 4216bc7e3467f7dc68f17370664ee11eda759db1 (PR #373).
Not sure how I missed that v7 converts to ESM
> Revert "STCLI-262 upgrade @formatjs/cli packages (#373)"

- CHANGELOG.md
- package.json
This reverts commit 69b4aef7df3204731eb8dd464162b23a68147096.
The Jenkins nodes where we build platform-complete don't yet have NodeJS v20 and we don't know when it will be available. In the interest of making other changes (which, AFAIK, do directly not rely on NodeJS v20) available ASAP, we are reverting this change until our build nodes can support it.
Refs [STCLI-260](https://folio-org.atlassian.net/browse/STCLI-260)
> Revert "STCLI-260 bump NodeJS to v20 (#371)"

- CHANGELOG.md
- package.json
Bump `@folio/stripes-webpack` to `~5.1.1`.
Refs [STCLI-264](https://folio-org.atlassian.net/browse/STCLI-264)
> STCLI-264 bump @folio/stripes-webpack to ~5.1.1

- CHANGELOG.md
- package.json
Bump `@folio/stripes-webpack` to `~5.2.1`.
Refs [STCLI-263](https://folio-org.atlassian.net/browse/STCLI-263)
> STCLI-263 bump @folio/stripes-webpack to ~5.2.1

- CHANGELOG.md
- package.json
Bump `webpack` to `^5.99.3` to avoid hiccups in the early `5.99.x` releases, e.g. https://github.com/webpack/webpack/issues/19394. Replaces PR #386.
Refs [STCLI-268](https://folio-org.atlassian.net/browse/STCLI-268)
> STCLI-268 bump webpack to ^5.99.6
